language: node_js
node_js:
  - "10"
branches:
  only:
    - master
    - gh-pages

jobs:
  include:
    - stage: "Test"
      name: "Testing Vue"
      script: 
        npm run test:unit
    - stage: "Build"
      name: "Building App"
      script: 
        npm run build
    - stage: "Deploy"
      name: "GH-pages Deploy"
      deploy:
        local_dir: dist
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  
        keep_history: true
        on:
          branch: gh-pages